### ISSUE TITLE
DB not init

### ISSUE THREAD

**Issue by oxycash** [aog11/postgresql-patroni-pgbouncer#1]
Hi,

I would like to know if this work for you, because when I try the db wasnt initiated and the manual application of patroni.yml fails.

Also the pg_hba has pgbouncer node in it.

**Comment by aog11** [comment]
Hi,

It's been a while since I last played with this, but I remember I had no issues running the Ansible playbooks for the setup of this lab; could you please share the error you are getting?

Regarding the pg_hba file, I normally include there all the machines from where I expect a connection to my postgres server, that might be the reason why you are seeing it there.

**Comment by aog11** [comment]
Hi @oxycash, just made some tweaks to this deployment, let me know if you still have issues.

**Comment by aog11** [comment]
Inactivity.
